services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_service_app
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_service_db
       SPRING_DATASOURCE_USERNAME: postgres
       SPRING_DATASOURCE_PASSWORD: postgres
       SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:15
    container_name: task_service_db
    environment:
      POSTGRES_DB: task_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
