spring:
  application:
    name: task-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task-service
    username: student
    password: 123
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyMzM5MzA5MCwiaWF0IjoxNzIzMzkzMDkwfQ.kjwrWbq89LXJCp20dVdDJa6hw55uScNVfk4hA4cYQLQ
  expiration: 24h

